//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProviderList
    {
        public int Id { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
