//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleList
    {
        public int Id { get; set; }
        public int MaterialId { get; set; }
        public int CheckId { get; set; }
        public int Amount { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Material Material { get; set; }
    }
}
